# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.12.8                 # https://pyreadiness.org/3.10
  - pip=24.3.1                    # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - BeautifulSoup4=4.10.0         # https://pypi.org/project/beautifulsoup4
  - numpy=2.1.0                   # https://pypi.org/project/numpy
  - pytesseract=0.3.10            # https://pypi.org/project/pytesseract
  - opencv=4.10.0                 # https://pypi.org/project/opencv-python

  - pip:
    - rpaframework==29.0.0        # https://rpaframework.org/releasenotes.html
    - robocorp==2.1.2             # https://pypi.org/project/robocorp
    - robocorp-browser==2.3.4     # https://pypi.org/project/robocorp-browser
  # - post_install:
    # - cmd.exe /c "curl -L -o tesseract-installer.exe https://github.com/UB-Mannheim/tesseract/wiki/tesseract-ocr-w64-setup-v5.0.0-alpha.20201127.exe && tesseract-installer.exe /SILENT"