name: CI

on:
  push:
    branches:
      - main
      - SOLID-updates
      - Github_actions
  pull_request:
    branches:
      - main
      - SOLID-updates
      - Github_actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: conda.yaml
        auto-activate-base: false

    - name: Install dependencies
      run: conda env update --file conda.yaml --name base

    - name: Run tests
      run: |
        python -m unittest discover -s . -p "test_*.py"